repos:
  - repo: https://github.com/sqlfluff/sqlfluff
    rev: 3.0.0
    hooks:
      - id: sqlfluff-lint
        args: [--dialect, clickhouse]
      - id: sqlfluff-fix
        args: [--dialect, clickhouse]
